//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by radTuner.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDD_FORMVIEW_SCRIPT             101
#define IDC_POINTER_MOVE_OBJECT         105
#define IDR_MAINFRAME                   128
#define IDR_RADTUNTYPE                  129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR256                  151
#define IDB_TOOLBARCOLD256              152
#define IDD_DIALOG_PROJECT_SETTING      153
#define IDR_MENU_SCRIPT_DOC             154
#define IDR_MENU_SCRIPT_OBJECT          155
#define IDR_MENU_SCRIPT_METHOD          157
#define IDD_DIALOG_ADD_NEW_OBJECT       158
#define IDD_DIALOG_ADD_NEW_METHOD       159
#define IDD_FORMVIEW_METHOD             160
#define IDD_FORMVIEW_PARAM_INT          161
#define IDD_FORMVIEW_PARAM_UINT         162
#define IDD_FORMVIEW_PARAM_BOOL         163
#define IDD_FORMVIEW_PARAM_STRING       164
#define IDD_FORMVIEW_PARAM_REF          165
#define IDD_FORMVIEW_PARAM_BASE_CLASS   166
#define IDD_DIALOG_MODIFIY_METHOD       167
#define IDD_DIALOG_MODIFY_OBJECT        168
#define IDB_USERIMAGES                  170
#define IDC_POINTER_MOVE_FILE           173
#define IDC_POINTER_MOVE_METHOD         174
#define IDR_MENU_CLASS_VIEW             175
#define IDD_DIALOG_SLIDER_SETTING       176
#define IDD_DIALOG_PARAM_SLIDER         177
#define IDR_MENU_PARAM_SLIDER           179
#define IDD_DIALOG_PARAM_SLIDER_TITLE_TEXT 180
#define IDB_BITMAP_SLIDER_BAR           182
#define IDB_BITMAP_SLIDER_BK            183
#define IDD_DIALOG_ENTER_SLIDER_VALUE   185
#define IDC_COMPANY_URL                 1041
#define IDC_EDIT_RTI_PATH               1044
#define IDC_BUTTON_RTI_BROWSE           1045
#define IDC_EDIT_SCRIPT_PATH            1046
#define IDC_BUTTON_SCRIPT_BROWSE        1047
#define IDC_COMBO_CLASS_LIST            1047
#define IDC_EDIT_OBJECT_NAME            1048
#define IDC_RADIO_CREATE                1049
#define IDC_EDIT_CLASS_NAME             1049
#define IDC_RADIO_WITH                  1050
#define IDC_COMBO_METHOD_LIST           1050
#define IDC_LIST_PARAMETER_LIST         1051
#define IDC_EDIT_CLASS_NAME2            1051
#define IDC_EDIT_METHOD_NAME            1056
#define IDC_EDIT_INT                    1057
#define IDC_EDIT_UINT                   1058
#define IDC_COMBO_BOOLEAN               1059
#define IDC_EDIT_STRING                 1060
#define IDC_COMBO_REF                   1061
#define IDC_COMBO_VALUE                 1065
#define IDC_EDIT_VALUE                  1066
#define IDC_TREE1                       1068
#define IDC_BUTTON_INVOKE               1069
#define IDC_CHECK_XBOX                  1070
#define IDC_CHECK_PC                    1071
#define IDC_CHECK_GCN                   1072
#define IDC_CHECK_PS2                   1073
#define IDC_CHECK_DEFAULT               1074
#define IDC_CHECK_ALL                   1075
#define IDC_BUTTON_HELP                 1076
#define IDC_EDIT_MAX                    1080
#define IDC_EDIT_STEP                   1080
#define IDC_EDIT_MIN                    1081
#define IDC_SLIDER_VALUE                1082
#define IDC_CMD_SLIDER_SETTING          1083
#define IDC_EDIT_CLASS                  1084
#define IDC_EDIT_METHOD                 1085
#define IDC_EDIT_TYPE                   1086
#define IDC_EDIT_NAME                   1087
#define IDC_SLIDER_TEST                 1088
#define IDC_EDIT_MAX_VALUE              1089
#define IDC_EDIT_MIN_VALUE              1090
#define IDC_BUTTON_REVERT               1093
#define IDC_BUTTON_ADD_VIEW             1094
#define IDC_EDIT_DESC                   1096
#define IDC_EDIT1                       1097
#define IDC_EDIT_TITLE_TEXT             1097
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_TOOLS_ENTRY                  32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_FILE_SAVE_ALL                32824
#define ID_PROJECT_SETTINGS             32829
#define ID_FILE_NEW_WORKSPACE           32830
#define ID_FILE_OPEN_WORKSPACE          32831
#define ID_FILE_SAVE_WORKSPACE          32832
#define ID_FILE_CLOSE_WORKSPACE         32833
#define ID_SCRIPTDOC_SAVE_SELECTED_SCRIPT 32837
#define ID_SCRIPTMETHOD_INVOKE_METHOD   32842
#define ID_SCRIPTOBJECT_SHOW            32843
#define ID_SCRIPTOBJECT_CALL            33024
#define ID_SCRIPT_NEW                   33281
#define ID_SCRIPT_DELETE                33282
#define ID_SCRIPT_DUPLICATE             33283
#define ID_SCRIPT_PROPERTIES            33284
#define ID_VIEW_REFRESH                 33285
#define ID_FILE_RELOADSCRIPTFILE        33286
#define ID_VIEW_CLEAROUTPUT             33287
#define ID_CLASS_CLEARALLMARK           33293
#define ID_CLASS_SELECTALL              33294
#define ID_SLIDER_TITLETEXT             33295
#define ID_SLIDER_AUTOUPDATE            33296
#define ID_SCRIPTOBJECT_RESETANDINVOKEALL 33297
#define ID_SLIDER_DESCRIPTION           33298
#define ID_SCRIPT_COPY                  33299
#define ID_SCRIPT_PASTE                 33301
#define ID_SLIDER_ENTERVALUEMANUALLY    33302
#define ID_FILE_RECENTWORKSPACES        33304
#define ID_PLATFORM_HELP_STRING         61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         33305
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
