//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by P3dexp.rc
//
#define IDS_TH_P3DSCENEFILE             1
#define IDS_TH_P3DMESH                  2
#define IDS_TH_MARK_JAMES               3
#define IDS_TH_COPYRIGHT_RADICAL        4
#define IDS_TH_P3DEXPORTDLL             5
#define IDS_TH_P3D                      6
#define IDS_TH_SCENEEXPORT              7
#define IDS_TH_P3DEXP                   8
#define IDS_TH_P3DEXPORTDLL_2           9
#define IDS_TH_P3DEXPORTDLL_beta        10
#define SCHTUPID                        11
#define IDD_P3DEXP_UI                   101
#define IDI_ICON1                       102
#define IDD_GlobalProperties            103
#define IDD_NODEANIM                    104
#define IDD_NODECOLL                    105
#define IDD_GEOMETRY                    107
#define IDD_ObjectProperties            108
#define IDD_DIALOG1                     109
#define IDD_HSplineProperties           109
#define IDD_LOGDIALOG                   110
#define IDD_GlobalPropertiesLite        111
#define IDC_LOGWARNING                  1001
#define IDC_LIST1                       1002
#define IDC_VERTEX                      1003
#define IDC_TRANSFORM                   1004
#define IDC_VERTNAME                    1005
#define IDC_TRANSNAME                   1006
#define IDC_TREE1                       1007
#define IDC_EXPGEO                      1010
#define IDC_chkExportGeo                1010
#define IDC_chkGeometries               1010
#define IDC_EXPVERT                     1011
#define IDC_chkExportVert               1011
#define IDC_chkVertAnim                 1011
#define IDC_EXPYTR                      1012
#define IDC_EXPTRAN                     1013
#define IDC_chkExportTrans              1013
#define IDC_chkTransAnim                1013
#define IDC_EXPTEX                      1014
#define IDC_EXPMAT                      1015
#define IDC_chkExportMat                1015
#define IDC_chkMatTex                   1015
#define IDC_DEFYTR                      1018
#define IDC_DEFTRAN                     1019
#define IDC_HASYTR                      1019
#define IDC_HASTRAN                     1020
#define IDC_NODEYTR                     1021
#define IDC_NODETRAN                    1022
#define IDC_HASVERT                     1023
#define IDC_NODEVERT                    1024
#define IDC_VERTLOOP                    1025
#define IDC_EDIT3                       1028
#define IDC_SPIN1                       1030
#define IDC_DODEFYTR                    1031
#define IDC_DODEFANIM                   1032
#define IDC_chkDefTransform             1032
#define IDC_BOUNDSPH                    1033
#define IDC_BOUNDBOX                    1034
#define IDC_COLLSPH                     1035
#define IDC_COLLBOX                     1036
#define IDC_COLLFACE                    1037
#define IDC_INSTNAME                    1041
#define IDC_INSTREF                     1042
#define IDC_edtDefTransform             1048
#define IDC_chkKeepJoint                1049
#define IDC_edtVertexAnimName           1051
#define IDC_radTransform                1052
#define IDC_TranformAnimName            1053
#define IDC_edtTranformAnimName         1053
#define IDC_CUSTOM3                     1054
#define IDC_edtSkinFilename             1054
#define IDC_edtSkinName                 1054
#define IDC_butBrowse                   1055
#define IDC_chkRemoveBiped              1057
#define IDC_radVertex                   1058
#define IDC_chkSkin                     1060
#define IDC_chkBillboard                1061
#define IDC_radETree                    1062
#define IDC_radMTree                    1063
#define IDC_radSTree                    1064
#define IDC_chkBillboards               1065
#define IDC_chkTrees                    1066
#define IDC_chkCompAnims                1067
#define IDC_chkLights                   1068
#define IDC_chkCameras                  1069
#define IDC_chkVertexAnim               1070
#define IDC_chkTransformNode            1071
#define IDC_chkTriangles                1072
#define IDC_edtTransAnimName            1073
#define IDC_edtDefTransName             1074
#define IDC_edtVertAnimName             1075
#define IDC_edtCBVAnimName              1076
#define IDC_edtUVAnimName               1077
#define IDC_chkGamedata                 1079
#define IDC_chkCBVAnim                  1080
#define IDC_chkUVAnim                   1081
#define IDC_chkDefTree                  1082
#define IDC_edtDefTreeName              1083
#define IDC_chkBGMap                    1084
#define IDC_chkBGColour                 1085
#define IDC_chkInPlaceNode              1086
#define IDC_cmbParentNode               1087
#define IDC_chkParentNode               1088
#define IDC_txtLOD                      1089
#define IDC_edtExRes                    1092
#define IDC_spnExRes                    1093
#define IDC_txtExResCaption             1094
#define IDC_chkHSTreeName               1095
#define IDC_edtHSTreeName               1097
#define IDC_chkHSKeepJoint              1098
#define IDC_chkHSTransAnimName          1099
#define IDC_edtHSTransAnimName          1100
#define IDC_chkHSOffsetAnimName         1101
#define IDC_edtHSOffsetAnimName         1102
#define IDC_radHSAbsOffAnim             1105
#define IDC_radHSRelOffAnim             1106
#define IDC_StreeRoot                   1107
#define IDC_chkStreeRoot                1107
#define IDC_chkKeyAtEveryFrame          1108

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
