/*===========================================================================
    Automatically generated by Jeeves, don't edit.  Edit p3dmutate.sc instead

    File: Param.hpp 

    Command line parameters for p3dmutate

       Provides a generic way to modify chunk fields

    Copyright (c) 2015 Radical Entertainment, Inc.  All rights reserved.

===========================================================================*/

#ifndef _PARAM_HPP
#define _PARAM_HPP

#include "tlTable.hpp"
#include "tlStringTable.hpp"

class tFile;
class tlDataChunk;

class Parameters
{

public:
    tlStringTable Files;

    Parameters(int argc, char* argv[]);
    ~Parameters();

    void          ShortUsage();                  //: Print a short usage message
    void          Usage();                       //: Print a usage message
    void          VersionHistory(int count = 1); //: Print version history
    tlDataChunk*  HistoryChunk();                //: Return a File History chunk

    // Tool specific parameters

   int           Query             ;//: Queries field values rather than updating
                                   //   them
   int           Edit              ;//: Updates field values (default behaviour)
   int           Delete            ;//: Deletes chunks rather than updating them
   char*         ChunkID           ;//: Specify list of chunk IDs to filter (eg. 
                                   //  0x3050-0x3058,0x305A)
   char*         NewChunkID        ;//: Convert chunks specified in ChunkID to
                                   //   these new IDs
   tlStringTable ChunkName         ;//: Specify chunk name filter (wildcards
                                   //   allowed, eg. Bone*)
   tlStringTable ParentName        ;//: Specify parent chunk name filter
                                   //   (wildcards allowed, eg. Skel*)
   tlStringTable TopParentName     ;//: Specify top-level parent chunk name
                                   //   filter (wildcards allowed)
   tlStringTable FieldName         ;//: Specify chunk field name filter
                                   //   (wildcards allowed, eg. *Name)
   tlStringTable FieldType         ;//: Specify chunk field type filter
                                   //   (wildcards allowed, eg. *WORD)
   char*         ArrayIndex        ;//: Specify list of array indices to filter
                                   //   (eg. 10-20,23)
   tlStringTable CurrentValue      ;//: Modify field only if current value
                                   //   matches filter (wildcards allowed)
   char*         NewValue          ;//: Specify new value for chunk field(s)
   int           PrefixFileName    ;//: Prefix new value for chunk field(s) with 
                                   //  current filename
   int           MaxCount          ;//: Limit number of fields updated/queried or
                                   //   number of chunks deleted to Value
   int           AppendOnly        ;//: Append new value not replace with.
   char*         OutputFile        ;//: Specify output file name
   int           IgnoreFieldFilter ;//: Continue processing even if no field name
                                   //   filter is specified (normally this is an
                                   //   error)

    // Standard parameters implemented by all tools

    int         Verbosity;                    //: How much noise should this program make?
    int         WriteHistory;                 //: Should the tool write a history chunk?

private:

   void filebuildup(char* filename);

   bool     isPattern;
   bool     Recurse;
   char* FilePattern;

    int      Argc;
    char**   Argv;
};

extern Parameters* Param;

#endif
