//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XCon.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_XCONTYPE                    129
#define IDD_NEW_FILE                    130
#define IDP_INVALID_RESOLUTION          130
#define IDS_TB_STANDARD                 131
#define IDD_SCREENS                     131
#define IDD_OVERLAYS                    132
#define IDS_STRING132                   132
#define IDD_RESOURCES                   133
#define ID_MESSAGES                     133
#define IDR_SCREEN                      134
#define IDP_FAILED_LOAD_CURSOR          134
#define IDR_OVERLAY                     135
#define IDP_FAILED_OPEN_FONT            135
#define IDR_RESOURCE                    136
#define IDP_INVALID_STRING              136
#define IDP_ERROR_LOADING_IMAGE         137
#define IDP_INVALID_NAME                138
#define IDP_RES_PATH_NOT_FOUND          139
#define IDR_XCONVIEW                    139
#define IDS_BROWSE_TITLE                140
#define IDD_DOC_PROPERTIES              140
#define IDS_ALL_FILTER                  141
#define IDD_IMAGE_PROPERTIES            141
#define IDP_ROOT_DRIVE_DIFFER           142
#define IDD_SPRITE_PROPERTIES           142
#define IDP_RESOURCE_ALREADY_LOADED     143
#define IDS_IMAGE_TITLE                 144
#define IDD_INSERT_SPRITE               144
#define IDS_IMAGE_FILTER                145
#define IDD_FONT_PROPERTIES             145
#define IDS_FONT_TITLE                  146
#define IDS_FONT_FILTER                 147
#define IDD_CURSOR_PROPERTIES           147
#define IDD_MULTI_OBJECT_PROPERTIES     148
#define IDS_TEXT_BIBLE_TITLE            148
#define IDD_INSERT_STRING               149
#define IDS_TEXT_BIBLE_FILTER           149
#define IDS_CURSOR_TITLE                150
#define IDD_STRING_PROPERTIES           150
#define IDS_CURSOR_FILTER               151
#define IDD_INSERT_TEXT                 151
#define IDP_ROOT_FOLDER_CHANGED         152
#define IDD_TEXT_PROPERTIES             152
#define IDS_NO_RES_PATH                 153
#define IDS_TEXT_STYLE_TITLE            154
#define IDP_ASK_TO_DELETE_RESOURCE      155
#define IDD_SCREEN_PROPERTIES           155
#define IDP_NO_OVERLAYS                 156
#define IDP_BITMAP_TOO_LARGE            157
#define IDD_TV_CUTOFF                   157
#define IDP_FAILED_TO_LOAD_FILE         158
#define IDP_INVALID_OBJECT              159
#define IDP_NO_OBJ_SELECTED             160
#define IDD_CLIP_PROPERTIES             160
#define IDP_TEXT_TOO_WIDE               161
#define IDI_XY                          161
#define IDS_EXPORT_TITLE                162
#define IDS_TEXT_STYLE_FILTER           163
#define IDP_FAILED_TO_EXPORT_DOC        164
#define IDS_ZOOM_IN                     165
#define IDD_PRIM_PROPERTIES             165
#define IDS_ZOOM_OUT                    166
#define IDP_NOT_ENOUGH_VERTECES         167
#define IDD_JSBAR                       167
#define IDS_LANGUAGE_TITLE              168
#define IDS_LANGUAGE_FILTER             169
#define IDP_OLE_INIT_FAILED             170
#define IDP_FAILED_LOAD_LANGUAGE        171
#define IDI_OUTPUT_DEBUG                171
#define IDP_FAILED_INVALID_LANGUAGE     172
#define IDI_OUTPUT_ERROR                172
#define IDP_SELECT_STRING_OR_ID         173
#define IDI_OUTPUT_FUNNY                173
#define IDP_JAPANESE_NOT_SUPPORTED      174
#define IDI_OUTPUT_INFORMATION          174
#define IDP_INVALID_FOLDER              175
#define IDI_OUTPUT_WARNING              175
#define IDP_EXPORT_PATH_NOT_FOUND       176
#define IDD_OUTPUT_WINDOW               176
#define IDP_QUERY_EXPORT_NO_SCREENS     177
#define IDP_INVALID_BITDEPTH            178
#define IDP_FAIL_START_PTUI             179
#define IDP_TIME_STAMP_INVALID          180
#define IDP_VERSION_CONFLICT            181
#define IDD_PROJECT_PROPERTIES          181
#define IDP_FAILED_OPEN_CLIPBOARD       182
#define IDP_CLIP_SELECT_OVERLAY         183
#define IDD_LAYER_ORGANIZER             183
#define IDP_CLIP_INVALID_DOCUMENT       184
#define IDD_MULTISPRITE_PROPERTIES      184
#define IDP_CLIP_INVALID_RES_PATH       185
#define IDP_CLIP_INVALID_LANG_PATH      186
#define IDP_CLIP_INVALID_RESOLUTION     187
#define IDS_SAVE_PROJECT_QUERY          188
#define IDR_OUTPUTWINDOW                189
#define IDR_OUTPUT_WINDOW               189
#define IDS_UNDO_STRING                 189
#define IDS_REDO_STRING                 190
#define IDS_MOVIECLIP_TITLE             191
#define IDS_PURE3DFILE_TITLE            192
#define IDS_MOVIECLIP_FILTER            193
#define IDS_PURE3DFILE_FILTER           194
#define IDI_EDITABLE                    197
#define IDI_EXPORTABLE                  198
#define IDI_VIEWABLE                    199
#define IDD_MULTITEXT_PROPERTIES        200
#define IDD_MULTITEXT_SELECT_PROPERTIES 201
#define IDI_TEXT_BIBLE_STRING           202
#define IDI_HARD_CODED_STRING           203
#define IDI_HARD_CODED_STRING_SELECT    204
#define IDI_TEXT_BIBLE_STRING_SELECT    205
#define IDI_SELECTED                    207
#define IDI_NOT_SELECTED                208
#define IDR_PROJECT                     209
#define IDI_MULTISPIRTE_IMAGE           209
#define IDI_MULTISPRITE_IMAGE_SELECTED  210
#define IDD_RESOURCE_PROPERTIES         210
#define IDD_LAYER_PROPERTIES            211
#define IDD_GROUP_PROPERTIES            212
#define IDD_MOVIE_PROPERTIES            213
#define IDD_PURE3DOBJECT_PROPERTIES     214
#define IDI_PURE3DFILE                  214
#define IDI_PURE3DFILE_SELECT           215
#define IDD_RESOURCE_P3D_PROPERTIES     215
#define IDI_MOVIE_SELECT                216
#define IDI_MOVIE                       217
#define IDI_ICON1                       218
#define IDD_SETTINGS_DIALOG             219
#define IDB_TREE1                       400
#define IDB_TREE2                       401
#define IDB_TREE3                       402
#define IDB_TREE4                       403
#define IDB_TREE5                       404
#define IDB_TREE6                       405
#define IDB_TREE7                       406
#define IDB_TREE8                       407
#define IDB_TREE9                       408
#define IDB_TREE10                      409
#define IDB_TREE11                      410
#define IDB_TREE12                      411
#define IDB_TREE13                      412
#define IDB_TREE14                      413
#define IDB_TREE15                      414
#define IDB_TREE16                      415
#define IDB_TREE17                      416
#define IDB_TREE18                      417
#define IDB_TREE19                      418
#define IDB_TREE20                      419
#define IDB_TREE21                      420
#define IDB_TREE22                      421
#define IDB_TREE23                      422
#define IDB_TREE24                      423
#define IDB_TREE25                      424
#define IDC_PSX                         1000
#define IDC_PC                          1001
#define IDC_WIDTH                       1002
#define IDC_HEIGHT                      1003
#define IDC_SPIN_WIDTH                  1004
#define IDC_SPIN_HEIGHT                 1005
#define IDC_TREE                        1006
#define IDC_PATH                        1008
#define IDC_RED                         1009
#define IDC_GREEN                       1010
#define IDC_BLUE                        1011
#define IDC_FILENAME                    1013
#define IDC_TRANSPARENT                 1014
#define IDC_REFRESH                     1015
#define IDC_COLOR                       1016
#define IDC_COLOR_BKGD                  1017
#define IDC_NAME                        1021
#define IDC_XPOS                        1022
#define IDC_YPOS                        1023
#define IDC_ALIGN_TOP                   1024
#define IDC_ALIGN_VCENTER               1025
#define IDC_ALIGN_BOTTOM                1026
#define IDC_ALIGN_LEFT                  1027
#define IDC_ALIGN_HCENTER               1028
#define IDC_ALIGN_RIGHT                 1029
#define IDC_COMBO                       1030
#define IDC_SEPARATION                  1036
#define IDC_CHARCODE                    1038
#define IDC_CHAR_LIST                   1039
#define IDC_PREVIEW                     1041
#define IDC_LIST                        1045
#define IDC_STRING                      1046
#define IDC_TRANSLATE                   1047
#define IDC_STRINGS                     1050
#define IDC_FONTS                       1051
#define IDC_NO_CHARS                    1064
#define IDC_ENABLE                      1067
#define IDC_HORZ_INSET                  1068
#define IDC_VERT_INSET                  1069
#define IDC_SPIN_HORZ                   1070
#define IDC_SPIN_VERT                   1071
#define IDC_LIST_AVAILABLE              1072
#define IDC_LIST_SELECTED               1073
#define IDC_ADD                         1074
#define IDC_REMOVE                      1075
#define IDC_MOVE_UP                     1076
#define IDC_MOVE_DOWN                   1077
#define IDC_SIZEIMAGE                   1078
#define IDC_TRANSLUCENT                 1079
#define IDC_RESET                       1081
#define IDC_LEFT                        1082
#define IDC_TOP                         1083
#define IDC_SPIN_LEFT                   1087
#define IDC_SPIN_TOP                    1088
#define IDC_PALETTES                    1091
#define IDC_BLOCKS                      1092
#define IDC_COMBO_ORIENTATION           1093
#define IDC_POSX_1                      1095
#define IDC_POSX_2                      1096
#define IDC_POSX_3                      1097
#define IDC_POSX_4                      1098
#define IDC_POSY_1                      1099
#define IDC_POSY_2                      1100
#define IDC_POSY_3                      1101
#define IDC_POSY_4                      1102
#define IDC_COLOR_1                     1103
#define IDC_COLOR_2                     1104
#define IDC_COLOR_3                     1105
#define IDC_COLOR_4                     1106
#define IDC_LANGUAGE                    1107
#define IDC_BROWSE                      1108
#define IDC_IDS                         1109
#define IDC_JAPANESE                    1113
#define IDC_FILENAME_JAP                1114
#define IDC_EXPORT_PATH                 1116
#define IDC_COPY                        1122
#define IDC_BROWSE_JAP                  1123
#define IDC_SPACING                     1124
#define IDC_SELECT                      1125
#define IDC_UNSELECT                    1126
#define IDC_SETFLAT                     1127
#define IDC_JS_TEXT                     1128
#define IDC_LIST1                       1130
#define IDC_TEXT_STYLE_LIST             1130
#define IDC_SETTINGS_VIEWERLIST         1130
#define IDC_EDIT_RESOLUTION_WIDTH       1131
#define IDC_TEXT_BIBLE_STRING_LIST      1131
#define IDC_EDIT_RESOLUTION_HEIGHT      1132
#define IDC_TEXT_BIBLE_LIST             1132
#define IDC_COMBO_PLATFORM              1133
#define IDC_EDIT_SCREEN_PATH            1134
#define IDC_EDIT_PAGE_PATH              1135
#define IDC_EDIT_RESOURCE_PATH          1136
#define IDC_IMAGE_RESOURCE_LIST_BOX     1137
#define IDC_IMAGE_NAME                  1138
#define IDC_CHOSEN_IMAGE_LIST_BOX       1138
#define IDC_FROM_TEXT_BIBLE_RADIO       1139
#define IDC_HARD_CODED_STRING_RADIO     1140
#define IDC_HARD_CODED_STRING           1141
#define IDC_TEXT_NAME                   1143
#define IDC_ALPHA_1                     1144
#define IDC_ALPHA_2                     1145
#define IDC_SET_TO_IMAGES_WIDTH_AND_HEIGHT 1145
#define IDC_ALPHA_3                     1146
#define IDC_ALIGN_TOP_LEFT              1146
#define IDC_ALPHA_4                     1147
#define IDC_LAYER_ORGANIZER_FRAME       1147
#define IDC_BUTTON1                     1148
#define IDC_ALIGN_TOP_CENTER            1149
#define IDC_TEXT_BIBLE_STRING_LIST_HIDE 1151
#define IDC_ALIGN_TOP_RIGHT             1152
#define IDC_BUTTON2                     1153
#define IDC_ADD_MULTITEXT_ITEM          1153
#define IDC_SETTINGS_BUTTON_WD_BROWSE   1153
#define IDC_BUTTON3                     1154
#define IDC_DELETE_MULTITEXT_ITEM       1154
#define IDC_ALIGN_CENTER_LEFT           1155
#define IDC_ALIGN_CENTER_CENTER         1156
#define IDC_ALIGN_CENTER_RIGHT          1157
#define IDC_ALIGN_BOTTOM_LEFT           1158
#define IDC_ALIGN_BOTTOM_CENTER         1159
#define IDC_ALIGN_BOTTOM_RIGHT          1160
#define IDC_BUTTON4                     1161
#define IDC_EDIT_MULTITEXT_ITEM         1161
#define IDC_BUTTON5                     1162
#define IDC_MULTI_TEXT_STRINGS          1164
#define IDC_DELETE_MULTISPRITE_ITEM     1165
#define IDC_RESOURCE_NAME               1166
#define IDC_ALPHA                       1171
#define IDC_MOVIE_RESOURCE_LIST_BOX     1174
#define IDC_PURE3DFILE_RESOURCE_LIST_BOX 1175
#define IDC_P3DPROP_INVENTORY           1176
#define IDC_P3DPROP_CAMERA              1177
#define IDC_P3DPROP_MULTICONTROLLER     1178
#define IDC_SETTINGS_FIELD_WD           1179
#define IDC_SETTINGS_FIELD_PCV          1180
#define IDC_SETTINGS_IPADDR_PS2V        1181
#define IDC_SETTINGS_BUTTON_PCV_BROWSE  1182
#define IDC_INVENTORY_NAME              1185
#define IDC_SHADOW_ENABLED              1187
#define IDC_SHADOW_ALPHA                1189
#define IDC_SHADOW_COLOUR               1190
#define IDC_SHADOW_OFFSET_X             1191
#define IDC_SHADOW_OFFSET_Y             1192
#define ID_INDICATOR_PLATFORM           32771
#define ID_INDICATOR_RES                32772
#define ID_INSERT_SCREEN                32773
#define ID_INDICATOR_XY                 32774
#define ID_PROPERTIES                   32776
#define ID_INSERT_OVERLAY               32777
#define ID_INSERT_STRING                32779
#define ID_INSERT_IMAGE                 32780
#define ID_INSERT_CURSOR                32783
#define ID_INSERT_FONT                  32784
#define ID_INSERT_SPRITE                32794
#define ID_INSERT_TEXT                  32795
#define ID_OVERLAY_SHOW                 32796
#define ID_OVERLAY_HIDE                 32797
#define ID_DELETE                       32798
#define ID_FILE_PROPERTIES              32799
#define ID_SCREEN_SHOW                  32800
#define ID_REFRESH                      32802
#define ID_OVERLAY_TOGGLE               32803
#define ID_OVERLAY_SHOW_ALL             32804
#define ID_OVERLAY_HIDE_ALL             32805
#define ID_MOVE_UP                      32806
#define ID_MOVE_DOWN                    32807
#define ID_FILE_EXPORT                  32808
#define ID_VIEW_TV_CUTOFF               32809
#define ID_MULTI_OBJECT                 32810
#define ID_ZOOM_TOGGLE                  32811
#define ID_INSERT_POLY                  32812
#define ID_INSERT_CLIP                  32813
#define ID_INSERT_LINE                  32815
#define ID_INSERT_TRIANGLE              32816
#define ID_INSERT_QUAD                  32817
#define ID_LANGUAGE_1                   32818
#define ID_LANGUAGE_2                   32819
#define ID_LANGUAGE_3                   32820
#define ID_LANGUAGE_4                   32821
#define ID_LANGUAGE_5                   32822
#define ID_LANGUAGE_6                   32823
#define ID_LANGUAGE_7                   32824
#define ID_LANGUAGE_8                   32825
#define ID_LANGUAGE_9                   32826
#define ID_LANGUAGE_10                  32827
#define ID_LANGUAGE_REFRESH             32828
#define ID_VIEW_PLAYSTATION             32829
#define ID_RENAME                       32830
#define ID_RESOURCE_USAGE               32831
#define ID_JS_EVAL                      32832
#define ID_JS_LOADTESTJS                32833
#define ID_JS_SAVETEXTFILE              32836
#define ID_JS_LOADTEXTFILE              32837
#define ID_INSERT_LAYER                 32838
#define ID_INSERT_GROUP                 32839
#define ID_VIEW_TOGGLE                  32840
#define ID_PROJECTTREE                  32841
#define ID_VIEW_PROJECT_WINDOW          32841
#define ID_FILE_OPEN_PROJECT            32842
#define ID_VIEW_OUTPUT_WINDOW           32843
#define ID_OUTPUT_WINDOW_COPY           32844
#define ID_OUTPUT_WINDOW_SAVE_FILE      32845
#define ID_FILE_CLOSE_PROJECT           32846
#define ID_FILE_SAVE_PROJECT            32847
#define ID_INSERT_TEXT_BIBLE            32849
#define ID_INSERT_TEXT_STYLE            32850
#define ID_OUTPUTWINDOWROOT_CLEAN       32853
#define ID_OUTPUT_WINDOW_CLEAN          32854
#define ID_INSERT_NEW_SCREEN            32855
#define ID_INSERT_EXISTING_SCREEN       32856
#define ID_FILE_PROJECT_PROPERTIES      32857
#define ID_FILE_NEW_PROJECT             32858
#define ID_VIEW_ZOOM_IN                 32859
#define ID_VIEW_ZOOM_OUT                32860
#define ID_VIEW_ACTUAL_PIXELS           32861
#define ID_FILE_INSERT_NEW_SCREEN       32862
#define ID_INSERT_NEW_PAGE              32863
#define ID_INSERT_EXISTING_PAGE         32864
#define ID_OVERLAY_EXPORT               32866
#define ID_LAYER_VISIBLE                32867
#define ID_LAYER_EDITABLE               32868
#define ID_ITEM_DUPLICATE               32869
#define ID_EDIT_DUPLICATE               32870
#define ID_INSERT_MULTISPRITE           32871
#define ID_INSERT_MULTITEXT             32874
#define ID_DELETE_SCREEN                32875
#define ID_ALIGN_TOP                    32876
#define ID_ALIGN_BOTTOM                 32877
#define ID_ALIGN_LEFT                   32878
#define ID_ALIGN_RIGHT                  32879
#define ID_ALIGN_VCENTER                32880
#define ID_ALIGN_HCENTER                32881
#define ID_EDIT_DESELECT_SELECTION      32882
#define ID_DELETE_PAGE                  32883
#define ID_DELETE_LAYER                 32884
#define ID_DEBUG_DUMP_UNDO_REDO_LIST    32885
#define ID_INSERT_MOVIE                 32886
#define ID_INSERT_PURE3DOBJECT          32887
#define ID_VIEW_REFRESH_ALL             32888
#define ID_EDIT_REFRESH_ALL             32889
#define ID_INSERT_MOVIE_CLIP            32890
#define ID_INSERT_PURE3DFILE            32891
#define ID_UNGROUP                      32892
#define ID_FILE_EXPORT_HASHED_NAMES     32893
#define ID_PREVIEWER_PS2                32895
#define ID_FILE_SAVEALL                 32896
#define ID_PREVIEW_PC                   32902
#define ID_EDIT_SETTINGS                32903

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32904
#define _APS_NEXT_CONTROL_VALUE         1193
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
