//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MemMonitor.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_MAIN_TOOLBAR                101
#define IDD_FORMVIEW_MEMORYSECTION_SUMMARY 101
#define IDD_FORMVIEW_MEMORYSPACE_SUMMARY 102
#define ID_INDICATOR_DATA_BUFFER        102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROPPAGE_TARGET             105
#define IDS_WINDOWS_MANAGER             107
#define IDC_CONFIG_SAVEAS_DEFAULT       108
#define IDR_MAINFRAME                   128
#define IDR_MMDTYPE                     129
#define IDR_POPUP_TOOLBAR               131
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR256                  151
#define IDB_TOOLBARCOLD256              152
#define IDB_BITMAP_MEMSECTION           153
#define IDB_BITMAP_MEMSPACE             154
#define IDR_MENU_SECTION_SUMMARY        156
#define IDR_MENU_SECTION_LIST           160
#define IDD_DIALOG_PROGRESS             161
#define IDB_TOOBAR_CELLVIEWCOLD256      163
#define IDB_TOOBAR_CELLVIEW256          164
#define IDR_CELLVIEW                    166
#define IDC_CURSOR_ZOOM                 168
#define IDR_MMCONTENT                   169
#define IDD_DIALOG_CELLVIEW_CONFIG      170
#define IDR_HEXEDIT                     171
#define IDD_PROPPAGE_COLOUR             171
#define IDD_PROPPAGE_FILE               172
#define IDB_TOOLBAR_HEXEDIT256          173
#define IDD_PROPPAGE_PDBLIST            173
#define IDB_TOOLBAR_HEXEDITCOLD256      174
#define IDR_MENU_HEXEDIT_DATAWIDTH      177
#define IDR_MENU_HEXEDIT_RELOADTIME     179
#define IDR_MENU_SECTION_RELOADTIME     180
#define IDR_MENU_BLOCK_VIEW             182
#define IDR_MENU_SECTION_CELLVIEW_PADDING 184
#define IDD_DIALOG_SECTION_LISTVIEW_PADDING 185
#define ID_BLOCKVIEW_COPYSTACKLIST      190
#define IDC_COMPANY_URL                 1041
#define IDC_RICHEDIT_SECTION_SUMMARY    1042
#define IDC_RICHEDIT_SUMMARY            1043
#define IDC_PROGRESS_LOAD               1050
#define IDC_EDIT_BYTES_PER_CELL         1051
#define IDC_EDIT_CELL_PER_ROW           1052
#define IDC_EDIT_CELL_SIZE_X            1053
#define IDC_EDIT_CELL_SIZE_Y            1054
#define IDC_IPADDRESS_TARGET_IP         1057
#define IDC_EDIT_TARGET_NAME            1058
#define IDC_BUTTON_ADD                  1059
#define IDC_BUTTON_REMOVE               1060
#define IDC_BUTTON_DEL                  1060
#define IDC_BUTTON_SET_AS_DEFAULT       1061
#define IDC_CHECK_IP_NAME               1063
#define IDC_CHECK_IP_ADDR               1064
#define IDC_EDIT_TARGET_IP_NAME         1065
#define IDC_LIST_TARGET_LIST            1066
#define IDC_EDIT_PORT                   1067
#define IDC_LIST_COLOUR_LIST            1068
#define IDC_EDIT_GROUP_ID               1070
#define IDC_COLOR_PICKER                1072
#define IDC_STATIC_RGB                  1073
#define IDC_EDIT_FILE_NAME              1074
#define IDC_EDIT_PS2_PDB_FILE           1074
#define IDC_EDIT_PADDING                1074
#define IDC_BUTTON_FILE_BROWSER         1075
#define IDC_BUTTON_PS2_PDB_FILE         1075
#define IDC_EDIT_GCN_PDB_FILE           1076
#define IDC_BUTTON_GCN_PDB_FILE         1077
#define IDC_EDIT_XBOX_PDB_FILE          1078
#define IDC_BUTTON_XBOX_PDB_FILE        1079
#define IDC_EDIT_PC_PDB_FILE            1080
#define IDC_BUTTON_PC_PDB_FILE          1081
#define IDC_EDIT_PS2_EXE_FILE           1082
#define IDC_BUTTON_PS2_EXE_FILE         1083
#define IDC_EDIT_GCN_EXE_FILE           1084
#define IDC_BUTTON_GCN_EXE_FILE         1085
#define IDC_EDIT_XBOX_EXE_FILE          1086
#define IDC_BUTTON_XBOX_EXE_FILE        1087
#define IDC_EDIT_PC_EXE_FILE            1088
#define IDC_BUTTON_PC_EXE_FILE          1089
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_VIEW_PROPERTY                32805
#define ID_WINDOW_MANAGER               32823
#define ID_SECTIONSUMMARY_VIEWSECTIONDETAIL 32823
#define ID_SECTIONSUMMARY_VIEWSECTIONMEMORY 32824
#define ID_SECTIONLIST_MEMORYCONTENT    32825
#define ID_CELLVIEW_OPTION              32826
#define ID_CELLVIEW_FIT                 32827
#define ID_CELLVIEW_ZOOM                32828
#define ID_HEXEDIT_FITWND               32829
#define ID_HEXEDIT_ADDRESS              32830
#define ID_HEXEDIT_ASCII                32831
#define ID_HEXEDIT_DWORD                32832
#define ID_HEXEDIT_WORD                 32833
#define ID_HEXEDIT_BYTE                 32834
#define ID_FILE_SETTINGS                32837
#define ID_HEXEDIT_ALIGNMENT            32838
#define ID_HEXEDIT_RELOAD               32840
#define ID_DATAWIDTH_BYTE               32841
#define ID_DATAWIDTH_WORD               32842
#define ID_DATAWIDTH_DWORD              32843
#define ID_HOST_CONNECT                 32844
#define ID_HOST_SUSPEND                 32845
#define ID_RELOADTIME_NONE              32846
#define ID_RELOADTIME_1SEC              32847
#define ID_RELOADTIME_2SEC              32848
#define ID_RELOADTIME_5SEC              32849
#define ID_RELOADTIME_10SEC             32850
#define ID_RELOADTIME_15SEC             32851
#define ID_RELOADTIME_20SEC             32852
#define ID_HOST_TARGETCONNECT           32853
#define ID_HOST_TARGETLIST              32854
#define ID_CELLVIEW_RELOAD              32855
#define ID_CELLVIEW_REFRESH             32856
#define ID_SECTIONRELOAD_NONE           32857
#define ID_SECTIONRELOAD_1SEC           32858
#define ID_SECTIONRELOAD_2SEC           32859
#define ID_SECTIONRELOAD_3SEC           32860
#define ID_SECTIONRELOAD_5SEC           32861
#define ID_SECTIONRELOAD_10SEC          32862
#define ID_BLOCKVIEW_CALLSTACKVIEW      32865
#define ID_BLOCKVIEW_REFOBJECTVIEW      32866
#define ID_CELLVIEWPADDING_8BYTES       32867
#define ID_CELLVIEWPADDING_16BYTES      32868
#define ID_CELLVIEWPADDING_24BYTES      32869
#define ID_CELLVIEWPADDING_32BYTES      32870
#define ID_CELLVIEWPADDING_CUSTOM       32871
#define ID_CELLVIEW_PADDING             32872
#define ID_CELLVIEWPADDING_0BYTES       32873
#define ID_FILE_SAVESETTINGSAS          32874
#define ID_FILE_LOADSETTINGS            32875
#define ID_FILE_SAVEAS                  32876
#define ID_BLOCKVIEW_CHILDOBJECTLIST    32877
#define ID_BLOCKVIEW_PARENTOBJECTLIST   32878
#define ID_CELLVIEWPADDING_64BYTES      32879
#define ID_CELLVIEWPADDING_128          32880
#define ID_CELLVIEWPADDING_128BYTES     32881
#define ID_BUTTON32882                  32882
#define ID_SECTIONSUMMARY_EXPORTDATA    32883
#define ID_SECTIONLIST_COPYADDRESS      32884

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        191
#define _APS_NEXT_COMMAND_VALUE         32886
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
